### ISSUE TITLE
www.schemasync.org not available

### ISSUE THREAD

**Issue by MartinNuc** [mmatuson/SchemaSync#37]
Domain probably expired. The link for how to install this doesnt work.

**Comment by mmatuson** [comment]
Thanks for letting me know! Domain is not expired, but I'm no longer using the provider where the website was hosted. 

I've moved it to Github Pages, at http://mmatuson.github.io/SchemaSync/ and updated the README with the new URLs. 

The install instructions can be found at http://mmatuson.github.io/SchemaSync/install.htm

I'm no longer working on this project but am open to finding it a new home.

**Comment by MartinNuc** [comment]
Thanks. I actually used pip for installing it :-)
