### ISSUE TITLE
No longer maintained

### ISSUE THREAD

**Issue by mmatuson** [mmatuson/SchemaSync#38]
I am no longer maintaining this project but am open to finding it a new home.

**Comment by blueness** [comment]
This is a good project.  I added it to Gentoo and used it during a massive db migration with good results.  I can't take over but I can look in from time to time and submit some fixes.

**Comment by lauri-elevant** [comment]
It has been incredibly useful for me as well. Does anyone know of an alternative tool?

**Comment by mmatuson** [comment]
@mitsh will be maintaining this project going forward, but contributors are always welcome.
