### ISSUE TITLE
sync_dropped_procedures error

### ISSUE THREAD

**Issue by jacoryjin** [mmatuson/SchemaSync#52]
def sync_dropped_procedures(src, dest):
    for p in dest:
        if p not in src:
            # yield dest[p].drop(), src[p].create() 
            yield dest[p].drop(), dest[p].create() # fix bug, key of p not in src, src[p].create() will be error

**Comment by Ulysses1988** [comment]
I met the problem, too

**Comment by jacoryjin** [comment]
@Ulysses1988 you can find the code and fixed it like me!
yield dest[p].drop(), dest[p].create()

**Comment by mmatuson** [comment]
Thank you, merged.

**Comment by Ulysses1988** [comment]
Thank you
