### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by heidji** [mmatuson/SchemaSync#63]
schemasync.org doesn't seem to belong to this project so I wouldn't know how to install it..

**Comment by heidji** [comment]
i managed to download the project using pip but nevertheless it would be really sad if it died because it seems to be the only way to migrate changes to production without manual labor

**Comment by mitsh** [comment]
half death, half alive. i cant improve this project anymore, because we changed our db servers mysql to mongo :/
if you improved or fixed issues, i and/or @mmatuson can accept your merge requests.

**Comment by heidji** [comment]
@mitsh just wanted to thank you dearly for this awesome project, because of it all of our deployments are fully automated since last summer. really really great work !
