### ISSUE TITLE
CREATE VIEW duplicate

### ISSUE THREAD

**Issue by heidji** [mmatuson/SchemaSync#65]
When the source schema has 1 view and the target schema has none, the CREATE VIEW line is added twice, and it looks like this:
```mysql
USE `db_dest`;
SET FOREIGN_KEY_CHECKS = 0;
// ... create new tables
SET FOREIGN_KEY_CHECKS = 1;
CREATE VIEW `view1` AS ... ;
SET FOREIGN_KEY_CHECKS = 1;
CREATE VIEW `view1` AS ... ;
```

**Comment by heidji** [comment]
when the view hasn't changed i also always get a duplicate 
```mysql
SET FOREIGN_KEY_CHECKS = 1;
```
at the end of the file which isn't a big problem. the main issue however is a game changer because i have to use "mysql -f" now

**Comment by heidji** [comment]
The [commit named 'merge' from 2016](https://github.com/mmatuson/SchemaSync/commit/1d8d034bddc89d8402caa9443da3b3fc73ced215) duplicates some lines without any explanation. I think it's an error

**Comment by mitsh** [comment]
@heidji thanks, i've merged your pull request.
